export const projects = [
  {
    id: 1,
    name: "Cal.com",
    description: "Scheduling infrastructure for absolutely everyone.",
    slug: "calcom",
    website: "https://cal.com",
    github: "https://github.com/calcom",
    tags: ["Next.js", "TypeScript", "React"],
    repos: ["https://api.github.com/repos/calcom/cal.com"],
  },
  {
    id: 2,
    name: "RailsDevs.com",
    description: "The reverse job board for Ruby on Rails developers.",
    slug: "railsdevs",
    website: "https://railsdevs.com",
    github: "https://github.com/joemasilotti/railsdevs.com",
    tags: ["Ruby on Rails", "Ruby"],
    repos: ["https://api.github.com/repos/joemasilotti/railsdevs.com"],
  },
  {
    id: 3,
    name: "Supabase",
    description: "The open source Firebase alternative.",
    tags: ["Next.js", "TypeScript", "React"],
    slug: "supabase",
    website: "https://supabase.com",
    github: "https://github.com/supabase",
    repos: ["https://api.github.com/repos/supabase/supabase"],
  },
  {
    id: 4,
    name: "Helicone",
    description: "Tooling for Generative AI",
    tags: ["Next.js", "TypeScript", "React"],
    slug: "helicone",
    website: "https://www.helicone.ai",
    github: "https://github.com/Helicone",
    repos: ["https://api.github.com/repos/Helicone/helicone"],
  },
  {
    id: 5,
    name: "Payload",
    description:
      "Built with React + TypeScript, Payload is a free and open-source Headless CMS.",
    tags: ["TypeScript", "React"],
    slug: "payloadcms",
    website: "https://payloadcms.com",
    github: "https://github.com/payloadcms",
    repos: ["https://api.github.com/repos/payloadcms/payload"],
  },
  {
    id: 6,
    name: "Mirrorful",
    description: "Create the building blocks of your app",
    tags: ["Next.js", "TypeScript", "React"],
    slug: "mirrorful",
    website: "https://mirrorful.com",
    github: "https://github.com/Mirrorful",
    repos: ["https://api.github.com/repos/Mirrorful/mirrorful"],
  },
  {
    id: 7,
    name: "Infisical",
    description:
      "♾ Infisical is an open-source, end-to-end encrypted platform for secret management: sync secrets across your team/infrastructure and prevent secret leaks.",
    tags: ["Next.js", "TypeScript", "React"],
    slug: "infisical",
    website: "https://infisical.com",
    github: "https://github.com/Infisical",
    repos: ["https://api.github.com/repos/Infisical/infisical"],
  },
  {
    id: 8,
    name: "highlight.io",
    description:
      "highlight.io: The open source, full-stack monitoring platform. Error monitoring, session replay, logging and more.",
    tags: ["Golang", "TypeScript"],
    slug: "highlight",
    website: "https://www.highlight.io",
    github: "https://github.com/highlight",
    repos: ["https://api.github.com/repos/highlight/highlight"],
  },
  {
    id: 9,
    name: "Reworkd",
    description:
      "Assemble, configure, and deploy autonomous AI Agents in your browser.",
    tags: ["Next.js", "TypeScript", "t3", "Python"],
    slug: "reworkd",
    website: "https://agentgpt.reworkd.ai",
    github: "https://github.com/reworkd",
    repos: ["https://api.github.com/repos/reworkd/AgentGPT"],
  },
  {
    id: 10,
    name: "Keep",
    description: "Open source alerts management platform",
    tags: ["Python", "Next.js", "TypeScript"],
    slug: "keep",
    website: "https://www.keephq.dev",
    github: "https://github.com/keephq",
    repos: ["https://api.github.com/repos/keephq/keep"],
  },
  {
    id: 11,
    name: "Nango",
    description:
      "Open-source product integration: Easily integrate you app with any external API",
    tags: ["TypeScript", "React"],
    slug: "nango",
    website: "https://www.nango.dev",
    github: "https://github.com/NangoHQ",
    repos: ["https://api.github.com/repos/NangoHQ/nango"],
  },
  {
    id: 12,
    name: "Trigger.dev",
    description:
      "✨ Trigger.dev is an open-source platform that makes it easy for developers to create event-driven background tasks directly in their code.",
    tags: ["React", "TypeScript"],
    slug: "triggerdotdev",
    website: "https://www.trigger.dev",
    github: "https://github.com/triggerdotdev",
    repos: ["https://api.github.com/repos/triggerdotdev/trigger.dev"],
  },
  {
    id: 13,
    name: "Flower",
    description: "Flower: A Friendly Federated Learning Framework",
    tags: ["Python"],
    slug: "flower",
    website: "https://flower.dev",
    github: "https://github.com/adap",
    repos: ["https://api.github.com/repos/adap/flower"],
  },
  {
    id: 14,
    name: "Lotus",
    description: "Open Source Pricing & Packaging Infrastructure",
    tags: ["Python", "Django", "React", "TypeScript"],
    slug: "lotus",
    website: "https://www.uselotus.io",
    github: "https://github.com/uselotus",
    repos: ["https://api.github.com/repos/uselotus/lotus"],
  },
  {
    id: 15,
    name: "Supertokens",
    description:
      "Open source alternative to Auth0 / Firebase Auth / AWS Cognito",
    tags: ["React", "TypeScript"],
    slug: "supertokens",
    website: "https://supertokens.com",
    github: "https://github.com/supertokens",
    repos: ["https://api.github.com/repos/supertokens/dashboard"],
  },
  {
    id: 16,
    name: "Forem",
    description:
      "Forem is open source software for building communities. Communities for your peers, customers, fanbases, families, friends, and any other time and space where people need to come together to be part of a collective.",
    tags: ["Ruby On Rails", "Ruby", "Preact", "TypeScript"],
    slug: "forem",
    website: "https://www.forem.com",
    github: "https://github.com/forem",
    repos: [
      "https://api.github.com/repos/forem/forem",
      "https://api.github.com/repos/forem/DEV-Android",
      "https://api.github.com/repos/forem/DEV-ios",
    ],
  },
  {
    id: 17,
    name: "Sylius",
    description: "Open Source eCommerce Framework on Symfony",
    tags: ["Symfony", "PHP"],
    slug: "sylius",
    website: "https://sylius.com",
    github: "https://github.com/Sylius",
    repos: ["https://api.github.com/repos/Sylius/Sylius"],
  },
  {
    id: 18,
    name: "Invoice Ninja",
    description:
      "Free Invoicing Software for Small Businesses built with Laravel, Flutter and React",
    tags: ["Laravel", "PHP", "Flutter", "Dart", "React", "TypeScript"],
    slug: "invoiceninja",
    website: "https://invoiceninja.com/",
    github: "https://github.com/invoiceninja",
    repos: [
      "https://api.github.com/repos/invoiceninja/invoiceninja",
      "https://api.github.com/repos/invoiceninja/ui",
      "https://api.github.com/repos/invoiceninja/admin-portal",
    ],
  },
];
